export const defaultTheme = {
  title: "",
  bg: {
    primary: "",
    secondary: "",
    success: "",
    danger: "",
    warning: "",
    info: "",
    body: "",
    default: "",
    light: "",
    dark: "",
  },
  fg: {
    primary: "",
    secondary: "",
    success: "",
    danger: "",
    warning: "",
    info: "",
    body: "",
    default: "",
    light: "",
    dark: "",
  },
};
